# This file was generated by GoReleaser. DO NOT EDIT.
cask "asactl" do
  name "asactl"
  desc "CLI for managing Apple Search Ads from YAML desired-state files"
  homepage "https://github.com/robaerd/asactl"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asactl"

  on_macos do
    on_intel do
      url "https://github.com/robaerd/asactl/releases/download/v#{version}/asactl_#{version}_darwin_amd64.tar.gz"
      sha256 "b1503116eba789c43af502baa04adb1781c7960dae9225f9e9b114d5444d0d3a"
    end
    on_arm do
      url "https://github.com/robaerd/asactl/releases/download/v#{version}/asactl_#{version}_darwin_arm64.tar.gz"
      sha256 "fce8bc1c8541f01784fae3e70f84d2899087818b1964eab7b187c346e8668497"
    end
  end

  caveats do
    "Run `asactl config init` and `asactl config edit` before your first `check-auth`, `plan`, or `apply`."
  end

  # No zap stanza required
end
