# This file was generated by GoReleaser. DO NOT EDIT.
cask "asactl" do
  name "asactl"
  desc "CLI for managing Apple Search Ads from YAML desired-state files"
  homepage "https://github.com/robaerd/asactl"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asactl"

  on_macos do
    on_intel do
      url "https://github.com/robaerd/asactl/releases/download/v#{version}/asactl_#{version}_darwin_amd64.tar.gz"
      sha256 "86fc555ba13f0ee6b064f2a4e470962ef3e4d8c0163ccd8bd030d2756af7d295"
    end
    on_arm do
      url "https://github.com/robaerd/asactl/releases/download/v#{version}/asactl_#{version}_darwin_arm64.tar.gz"
      sha256 "da4b75065aaff054868b1ce96ba83511ca5351f30ce91c07332e4169ef61cebd"
    end
  end

  caveats do
    "Run `asactl config init` and `asactl config edit` before your first `check-auth`, `plan`, or `apply`."
  end

  # No zap stanza required
end
