# This file was generated by GoReleaser. DO NOT EDIT.
cask "tempotui" do
  name "tempotui"
  desc "Terminal UI for reviewing Tempo monthly worklogs and adjusting start times"
  homepage "https://github.com/robaerd/tempotui"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tempotui"

  on_macos do
    on_intel do
      url "https://github.com/robaerd/tempotui/releases/download/v#{version}/tempotui_#{version}_darwin_amd64.tar.gz"
      sha256 "48275f55f8d4a93ade82a4cf08717464dc5b1c8ce3647819091097cf3fa7411c"
    end
    on_arm do
      url "https://github.com/robaerd/tempotui/releases/download/v#{version}/tempotui_#{version}_darwin_arm64.tar.gz"
      sha256 "248bc9248f6047f62dfbb1378a955a5741ae3bdd4860e534bf6bddb97341226c"
    end
  end

  caveats do
    "On first launch, open tempotui and add your Tempo and Jira credentials in Settings."
    "The config file is stored at ~/.config/tempotui/config.toml unless XDG_CONFIG_HOME is set."
  end

  # No zap stanza required
end
